run:build
	@./bin/dump --path="../server/git_server/internal/file" --user="SyedDevop"
runPrime:build
	@./bin/dump --path="../server/git_server/internal/file" --user="thePrimeagen"

build:
	@go build  -o ./bin/
