run:build
	@./bin/dump --path="../server/git_server/internal/file" --file="SyedDevop"

runPrime:build
	@./bin/dump --path="../server/git_server/internal/file" --file="thePrimeagen"

build:
	@go build  -o ./bin/
