run:build
	@./bin/dump --path="../server/git_server/internal/file" --file="SyedDevop"
runRepo:build
	@./bin/dump --path="../server/git_server/internal/file" --file="SyedDevop" --data="repo"
runPrime:build
	@./bin/dump --path="../server/git_server/internal/file" --file="thePrimeagen"

build:
	@go build  -o ./bin/
